In [1]:
import numpy as np
import data_preprocessing
import PyEDCR

# Creating test_data

In [6]:
# test_pred_fine = np.load('test/test_pred_fine.npy')
# test_pred_coarse = np.load('test/test_pred_coarse.npy')

train_fine_pred = np.load('combined_results/vit_b_16_train_fine_pred_BCE_lr0.0001_e19.npy')
train_coarse_pred = np.load('combined_results/vit_b_16_train_coarse_pred_BCE_lr0.0001_e19.npy')
test_fine_pred = np.load('combined_results/vit_b_16_test_fine_pred_BCE_lr0.0001_e19.npy')
test_coarse_pred = np.load('combined_results/vit_b_16_test_coarse_pred_BCE_lr0.0001_e19.npy')

test_fine_true, test_coarse_true = data_preprocessing.get_ground_truths(test=True,)
train_fine_true, train_coarse_true = data_preprocessing.get_ground_truths(test=False)

In [7]:
import numpy as np

# Initialize empty lists to store indices for each value
indices_list_train = []

# Iterate through each unique value and limit to 10 instances
for value in [0, 1, 2]:
    # Get indices where the value is present
    indices = np.where(train_fine_true == value)[0]
    
    # Limit to 10 instances and shuffle the indices
    indices = np.random.choice(indices, size=10, replace=False)
    
    # Append the limited indices to corresponding lists
    indices_list_train.extend(indices)

In [8]:
import numpy as np

# Initialize empty lists to store indices for each value
indices_list_test = []

# Iterate through each unique value and limit to 10 instances
for value in [0, 1, 2]:
    # Get indices where the value is present
    indices = np.where(test_fine_true == value)[0]
    
    # Limit to 10 instances and shuffle the indices
    indices = np.random.choice(indices, size=10, replace=False)
    
    # Append the limited indices to corresponding lists
    indices_list_test.extend(indices)

In [9]:
check_train_fine_pred = train_fine_pred[indices_list_train]
check_train_coarse_pred = train_coarse_pred[indices_list_train]

check_test_fine_pred = test_fine_pred[indices_list_test]
check_test_coarse_pred = test_coarse_pred[indices_list_test]

check_train_fine_true = train_fine_true[indices_list_train]
check_train_coarse_true = train_coarse_true[indices_list_train]

check_test_fine_true = test_fine_true[indices_list_test]
check_test_coarse_true = test_coarse_true[indices_list_test]

In [13]:
np.save("test_data/check_train_fine_pred.npy", check_train_fine_pred)
np.save("test_data/check_train_coarse_pred.npy", check_train_coarse_pred)

np.save("test_data/check_test_fine_pred.npy", check_test_fine_pred)
np.save("test_data/check_test_coarse_pred.npy", check_test_coarse_pred)

np.save("test_data/check_train_fine_true.npy", check_train_fine_true)
np.save("test_data/check_train_coarse_true.npy", check_train_coarse_true)

np.save("test_data/check_test_fine_true.npy", check_test_fine_true)
np.save("test_data/check_test_coarse_true.npy", check_test_coarse_true)

# Retrieve check data

In [2]:
check_train_fine_pred = np.load("test_data/check_train_fine_pred.npy")
check_train_coarse_pred = np.load("test_data/check_train_coarse_pred.npy")

check_test_fine_pred = np.load("test_data/check_test_fine_pred.npy")
check_test_coarse_pred = np.load("test_data/check_test_coarse_pred.npy")

check_train_fine_true = np.load("test_data/check_train_fine_true.npy")
check_train_coarse_true = np.load("test_data/check_train_coarse_true.npy")

check_test_fine_true = np.load("test_data/check_test_fine_true.npy")
check_test_coarse_true = np.load("test_data/check_test_coarse_true.npy")

In [36]:
check_test_fine_pred

array([ 0,  0,  0,  0,  0,  0,  0, 19,  1,  0, 10,  1,  2,  1, 11,  1,  1,
        1,  1,  1,  2, 15,  2,  2,  8, 23, 23, 23,  2,  2])

In [37]:
check_test_fine_true

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [41]:
np.where(check_test_coarse_pred == check_test_coarse_true, 1, 0)

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1])

In [18]:
label = data_preprocessing.get_labels(data_preprocessing.granularities[1])
label[0]._l_str

'Air Defense'

In [21]:
data_preprocessing.coarse_grain_classes_str

['Air Defense',
 'BMD',
 'BMP',
 'BTR',
 'MT_LB',
 'Self Propelled Artillery',
 'Tank']

In [40]:
!python test_PyEDCR/test_get_where_predicted_correct.py

####################################################################################################
Main model name: False with False loss on the train dataset
with lr=False

Fine-grain prior individual accuracy: 80.0%, fine-grain prior individual macro f1: 10.89%
Fine-grain prior individual macro precision: 12.08%, fine-grain prior individual macro recall: 10.0%

Coarse-grain prior individual accuracy: 86.67%, coarse-grain prior individual macro f1: 25.64%
Coarse-grain prior individual macro precision: 26.35%, coarse-grain prior individual macro recall: 25.0%

Total prior inconsistencies 0/30 (0.0%)

####################################################################################################
Main model name: False with False loss on the test dataset
with lr=False

Fine-grain prior individual accuracy: 66.67%, fine-grain prior individual macro f1: 9.55%
Fine-grain prior individual macro precision: 11.28%, fine-grain prior individual macro recall: 8.33%

Coarse-grain prior indi